### ISSUE TITLE
 Target [JoelButcher\Socialstream\Contracts\UpdatesConnectedAccounts] is not instantiable while building [JoelButcher\Socialstream\Http\Controllers\OAuthController].

### ISSUE THREAD

**Issue by jrbautista10** [joelbutcher/socialstream#102]
When running php artisan route:list I get this error

 Target [JoelButcher\Socialstream\Contracts\UpdatesConnectedAccounts] is not instantiable while building [JoelButcher\Socialstream\Http\Controllers\OAuthController].

![image](https://user-images.githubusercontent.com/37645059/114441073-7e202880-9bfd-11eb-827b-feba50c5021e.png)

**Comment by joelbutcher** [comment]
This is addressed in the [upgrade guide](https://github.com/joelbutcher/socialstream/blob/3.x/UPGRADE.md). Please refer to the `Create Connected Account Action` section detailed within the instructions for upgrading from 1.x to 2.x.
