### ISSUE TITLE
To supple Apple 

### ISSUE THREAD

**Issue by horaceho** [joelbutcher/socialstream#103]
**What problem does this feature request solve?.**
To support login with Apple 

**Describe your proposed solution**
To support login with Apple https://socialiteproviders.com/Apple/#installation-basic-usage

**Describe alternatives you've considered**
Manually: https://socialiteproviders.com/Apple/#installation-basic-usage

**Environment context**
- Socialstream version: 3.0.1
- Jetstream stack: Livewire
- Laravel version: 8.37.0
- PHP version: 7.4.3

**Comment by joelbutcher** [comment]
I've purposefully restricted the providers this package supports to just those provided supported by the first-party Laravel package, Socialite. If you wish to include additional providers not supported by the Laravel team, you will need to implement this in your own app. Alternatively, you are free to maintain a fork supporting the providers not listed within the Socialite documentation.
