### ISSUE TITLE
User should be able to delete his account even with no password set

### ISSUE THREAD

**Issue by wassim** [joelbutcher/socialstream#104]
Is there a specific reason for the following modification?

old
```javascript
<div v-if="$page.props.jetstream.hasAccountDeletionFeatures">
    <jet-section-border />

    <delete-user-form class="mt-10 sm:mt-0" />
</div>
```

new
```javascript
<div v-if="$page.props.socialstream.hasPassword">
    <jet-section-border />

    <delete-user-form class="mt-10 sm:mt-0" />
</div>
```

**Comment by joelbutcher** [comment]
Yes, it's a security flaw and jetstream by default requires a password to delete an account, so I've kept that functionality.

**Comment by joelbutcher** [comment]
@wassim see #107

**Comment by lsmith77** [comment]
for my clarification, this means until Jetstream supports deleting without password, socialstream will not support deleting of password-less users either? ie. if I want to allow password-less users to delete their account, I will need to take this up with jetstream maintainers?

semi-related I want to even make it possible to disable setting a password entirely on a team aka domain level, so that organizations can force the use of SSO.

**Comment by joelbutcher** [comment]
@lsmith77, yes the team at Laravel are responsible for disabling deleting an account without a password. They may publish a file on install, that you can override, but I can't guarantee it.

RE your SSO questions, is it not enough to just hide the forms with a condition?

```php
@if (! $organisation->supportsSso())
    <!-- Render form -->
@endif

**Comment by lsmith77** [comment]
yeah but I then also need to add some logic to the controller to check this. will have to see how I can do this somewhat cleanly. kinda wish that socialstream would be seen as part of jetstream core.

**Comment by lsmith77** [comment]
ah .. looks like I am digging up old “wounds” with my above statement as I just found https://github.com/laravel/jetstream/pull/444

I will look into this a bit more on the jetstream side to see what sort of extension points might be needed to make this work cleanly. if I have any findings (ie. ideally a PR) you will seen it soon enough.

**Comment by joelbutcher** [comment]
@lsmith77 Yup, don't go there... 😢
