### ISSUE TITLE
[bug]  OAuthController always redirect to config('fortify.home')

### ISSUE THREAD

**Issue by opilo** [joelbutcher/socialstream#108]
Login only redirects to config('fortify.home') and not the intended URL. Please add the intended helper to redirects in the handleProviderCallback method of LoginResponse class.

Thank you

**Comment by joelbutcher** [comment]
Hey @opilo thanks for this issue report 👍. I'm a little confused as to why this is marked as a 'bug' - what specifically is broken here 🤔?

As far as I can tell, what you've requested is a feature request and change in functionality. Personally I don't see the need for this 🤷‍♂️, but if you can provide an example use-case where this is causing an issue, @ me in your reply and I'll take a look.  

As always, I'm open to reviewing a PR for changes like this if they serve a common use-case! 😁

**Comment by opilo** [comment]
@joelbutcher Hello Joel, sorry for using the wrong tag. 
The Jetstream's default behavior is to redirect to the intended page when you log in using username and password, but if you use Socialstream, you will be redirected to the default page. So at this point the login mechanism acts in different ways which is not nice.
This causes issues where user is at a certain point, for example step 3 of a form wizard and the sessions expires. User has to navigate back to the step 3 all the way from home.

Thank you

**Comment by joelbutcher** [comment]
@opilo Created a bugfix branch for this in #109 Please can you test in your application?

**Comment by opilo** [comment]
@joelbutcher Doesn't work for login. The redirect on line 192 must also be changed in order to work.
Thank you

**Comment by joelbutcher** [comment]
@opilo just updated the PR

**Comment by opilo** [comment]
@joelbutcher closing bracket } is missing from the class. The logic works fine.
