### ISSUE TITLE
Callback action is returning a 404 page not found error

### ISSUE THREAD

**Issue by NielsvanHoof** [joelbutcher/socialstream#110]
**Describe the bug**
All callback routes return a 404 | Page not found error 

I tried the facebook and google providers, I can select my account but during the callback a 404 not found error is returned.
Both are configured in my services.php file like this

```
'google' => [
    'client_id' => env('GOOGLE_CLIENT_ID'),
    'client_secret' => env('GOOGLE_CLIENT_SECRET'),
    'redirect' => 'http://localhost:8000/auth/google/callback',
  ],

  'facebook' => [
    'client_id' => env('FACEBOOK_APP_ID'),
    'client_secret' => env('FACEBOOK_APP_SECRET'),
    'redirect' => 'http://localhost:8000/auth/facebook/callback',
  ],
```

**Screenshots**
[Screenshots of the issue](https://imgur.com/a/SvEz6C8)

- Socialstream version: 3.X
- Jetstream stack: Livewire
- Laravel version: 8.40.0
- PHP version: 8.0.1

**Comment by joelbutcher** [comment]
The callback is `/oauth/<provider>/callback` not `/oauth/<provider>/callback`
