### ISSUE TITLE
[ Getting an No such file or directory error after moving HandleInvalidState.php to other location]

### ISSUE THREAD

**Issue by seshac** [joelbutcher/socialstream#127]
**Describe the bug**
 Getting the **No such file or directory error** after moving HandleInvalidState.php to other location even after updating in SocialstreamServiceProvider.php 

**To Reproduce**
1. Go to ' Move App\Actions\Socialstream file to another location and update namespace in SocialstreamServiceProvider.php  '
2.  Try to connect any provider, and you can be able to see error.

**Expected behavior**

```
ErrorException
include(/Users/seshadrichandrappa/Sites/pingnow/vendor/composer/../../app/Actions/Socialstream/HandleInvalidState.php): Failed to open stream: No such file or directory
```

**Screenshots**

**Environment context**
- Socialstream version: ^3.0
- Jetstream stack: Inertia
- Laravel version: 8.40
- PHP version: 8.0

**Comment by joelbutcher** [comment]
Did you update the namespace in the file(s) that you moved?

**Comment by seshac** [comment]
> Did you update the namespace in the file(s) that you moved?

Yes, I did, but still getting an error.

I fixed and created a PR for this. I was wondering if you find some time to review my PR.


Thank you for this wonderful package.
