### ISSUE TITLE
use nickname as fallback on CreateUserFromProvider 

### ISSUE THREAD

**Issue by bskade** [joelbutcher/socialstream#13]
it could be that name is null, so no account would be created

**Comment by joelbutcher** [comment]
Do you have any examples of Socialite supported providers where this is the case?

**Comment by bskade** [comment]
for example github - here i just get my nickname. Maybe because I dont have a public profile

**Comment by joelbutcher** [comment]
Feel free to submit a PR

**Comment by joelbutcher** [comment]
@bskade do you plan on writing a PR for this?

**Comment by joelbutcher** [comment]
Closing this issue due to lack of participation

**Comment by Brouilles** [comment]
Like this @bskade?
https://github.com/joelbutcher/socialstream/pull/79
