### ISSUE TITLE
[bug] or error vendor/laravel/socialite/src/SocialiteManager.php:125 -  Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by kuaza61** [joelbutcher/socialstream#130]
![Ekran görüntüsü 2021-07-02 221648](https://user-images.githubusercontent.com/7365944/124325411-d3c4fb00-db84-11eb-9429-c19626ed8ca3.jpg)
**Describe the bug**
Unable to login with social media accounts. I get the error in the picture: ErrorException
Trying to access array offset on value of type null
https://domain.com/oauth/facebook

I tried every way but couldn't install properly. I reinstalled 4 times. The value for $config in the line here vendor/laravel/socialite/src/SocialiteManager.php:125 is null. What could be the reason for this? I have set the config/socialstream.php file correctly.

`<?php

use JoelButcher\Socialstream\Features;
use JoelButcher\Socialstream\Providers;

return [

    /*
    |--------------------------------------------------------------------------
    | Socialstream Route Middleware
    |--------------------------------------------------------------------------
    |
    | Here you may specify which middleware Socialstream will assign to the
    | routes that it registers with the application. When necessary, you may
    | modify these middleware; however, this default value is usually sufficient.
    |
    */

    'middleware' => ['web'],

    /*
    |--------------------------------------------------------------------------
    | Socialstream Providers
    |--------------------------------------------------------------------------
    |
    | Here you may specify the providers your application supports for OAuth.
    | Out of the box, Socialstream provides support for all of the OAuth
    | providers that are supported by Laravel Socialite.
    |
    */

    'providers' => [
        Providers::github(), // https://sorucevap.com/oauth/github/callback
        Providers::facebook(), // https://sorucevap.com/oauth/facebook/callback
        Providers::google(), // https://sorucevap.com/oauth/google/callback
    ],

	'github' => [
		'client_id' => "xxxxxx",
		'client_secret' => "xxxxxxx",
		'redirect' => 'https://domain.com/oauth/github/callback', // e.g. 'https://your-domain.com/oauth/{provider}/callback'
	],

	'facebook' => [
		'client_id' => "xxxxxxx",
		'client_secret' => "xxxxxxxxx",
		'redirect' => 'https://domain.com/oauth/facebook/callback', // e.g. 'https://your-domain.com/oauth/{provider}/callback'
	],

    /*
    |--------------------------------------------------------------------------
    | Features
    |--------------------------------------------------------------------------
    |
    | Some of Socialstreams's features are optional. You may disable the features
    | by removing them from this array. You're free to only remove some of
    | these features or you can even remove all of these if you need to.
    |
    */

    'features' => [
        // Features::createAccountOnFirstLogin(),
        // Features::generateMissingEmails(),
        Features::rememberSession(),
        Features::providerAvatars(),
    ],
];
`

**Expected behavior**
I want to make a healthy registration system. With social media registration option. I hope you can help me solve this problem. Thanks.

**Screenshots**
https://a1.depotic.com/images/2021/07/02/Ekran-goruntusu-2021-07-02-221648bf53c6cee633efdc.jpg

**Environment context**
- Socialstream version: v3.1.3
- Jetstream stack: Livewire
- Laravel version: 8.49.1
- PHP version: 7.4.20

**Comment by joelbutcher** [comment]
This isn't a bug with the package, but a bug with socialite providers. Having a quick look, your config is wrong. Client ids, secrets and redirect URI's should be inside the services.php config file.
