### ISSUE TITLE
Target [JoelButcher\Socialstream\Contracts\CreatesUserFromProvider] is not instantiable

### ISSUE THREAD

**Issue by lsmith77** [joelbutcher/socialstream#151]
**Describe the bug**
I just did a fresh installation of Jetstream (with Livewire), Socialite and your package.

When clicking on the "github" icon I receive

```
Target [JoelButcher\Socialstream\Contracts\CreatesUserFromProvider] is not instantiable while building [JoelButcher\Socialstream\Http\Controllers\OAuthController].
```

**To Reproduce**
1. Go to the login page
2. Click on github icon
3. I end up on https://.../oauth/github

**Expected behavior**
Github login page

**Screenshots**

**Environment context**
- Socialstream version: 3.2.2
- Jetstream stack: Livewire
- Laravel version:  v8.68.1
- PHP version:  8.0.12

**Comment by joelbutcher** [comment]
Just tried this on a fresh install and I can't replicate the issue. Please make sure you have the published actions in `app/Actions/Socialstream` and haven't tampered with your `SocialstreamServiceProvider` to remove the container bindings that are placed there on install.

**Comment by lsmith77** [comment]
thank you for taking the time to double check this. indeed after going through the process once more, everything works flawlessly.
