### ISSUE TITLE
OAuth2 for Twitter

### ISSUE THREAD

**Issue by imClement** [joelbutcher/socialstream#158]
Is there any plan to implement OAuth 2 for Twitter service?

Thank you.

**Comment by joelbutcher** [comment]
That's up to the maintainer for [laravel/socialite](https://github.com/laravel/socialite). This package isn't responsible for which OAuth versions are used, sorry.

**Comment by WizardOfCodez** [comment]
@joelbutcher Socialite now has an OAuth2 provider for twitter by default: https://github.com/laravel/socialite/blob/5.x/src/SocialiteManager.php ('twitter-oauth-2')

Since I am currently playing around with socialstream: Is it possible to use it out of the box?

**Comment by joelbutcher** [comment]
@WizardOfCodez I've not tried this. Theoretically should be possible as we are if you cater for the provider in the Socialstream components. I'll look at supporting Twitter OAuth 2 this weekend.

**Comment by joelbutcher** [comment]
Resolved with #206 – see release [v3.7.1](https://github.com/joelbutcher/socialstream/releases/tag/v3.7.1)

**Comment by WizardOfCodez** [comment]
@joelbutcher works great but I think there is an issue on the Providers.vue that gets bootstrapped. Instead of

`      <a
        v-if="
          $page.props.socialstream.providers.includes('twitter') ||
          $page.props.socialstream.providers.includes('twitter-oauth-2')
        "
        :href="route('oauth.redirect', 'twitter')"
      >
        <TwitterIcon class="h-6 w-6 mx-2" />
        <span class="sr-only">Twitter</span>
      </a>`

shouldn't it be

`      <a
        v-if="$page.props.socialstream.providers.includes('twitter')"
        :href="route('oauth.redirect', 'twitter')"
      >
        <TwitterIcon class="h-6 w-6 mx-2" />
        <span class="sr-only">Twitter</span>
      </a>

      <a
        v-if="$page.props.socialstream.providers.includes('twitter-oauth-2')"
        :href="route('oauth.redirect', 'twitter-oauth-2')"
      >
        <TwitterIcon class="h-6 w-6 mx-2" />
        <span class="sr-only">Twitter</span>
      </a>`
      
     The oauth.redirect route for 'twitter' is still for oauth v1

**Comment by joelbutcher** [comment]
Can you raise an issue and possibly send in a fix for this? Thanks!

**Comment by WizardOfCodez** [comment]
Yep, will do and also fix an additional minor bug

**Comment by WizardOfCodez** [comment]
https://github.com/joelbutcher/socialstream/pull/207
