### ISSUE TITLE
[bug] Temp path for avatar missing the trailing "/" for saving avatar

### ISSUE THREAD

**Issue by helloadmin** [joelbutcher/socialstream#167]
ErrorException
file_put_contents(/tmpcacf450d-a5b9-4f8f-8455-d65e88911b30): Failed to open stream: Permission denied

vendor/joelbutcher/socialstream/src/SetsProfilePhotoFromUrl.php:19

 file_put_contents($file = sys_get_temp_dir().Str::uuid()->toString(), file_get_contents($url));

It appears that sys_get_temp_dir() is returning /tmp and not including the trailing slash / 

/tmpcacf450d-a5b9-4f8f-8455-d65e88911b30

The man page for sys_get_temp_dir() says this is the behavior on some systems:
https://www.php.net/manual/en/function.sys-get-temp-dir.php

I'm using WHM/Cpanel with CloudOS

**Environment context**
- Socialstream version: #.#.#
- Jetstream stack: Inertia 
- Laravel version: 8.6
- PHP version: 8.0

**Comment by james-wong123** [comment]
yea, I had the same problem as well 
![image](https://user-images.githubusercontent.com/87692325/150337670-cf45e978-ecfc-4bb9-857a-e1638b424a68.png)
![image](https://user-images.githubusercontent.com/87692325/150337704-029c8bf2-f141-41ea-a0f8-05c4ab216fc5.png)

**Comment by Sairahcaz** [comment]
#169 I fixed it in this PR...
