### ISSUE TITLE
Providers.php not published?

### ISSUE THREAD

**Issue by rightwayround** [joelbutcher/socialstream#168]
Hi,

In the README it says:

> To implement a custom provider, you will need to create an SVG icon file (e.g. twitter-icon.blade.php or TwitterIcon.vue) to be used in the authentication cards and the account management panel.
> 
> You will then need to alter the appropriate published components with your new icons and provider condition:
> 
> Connected Account component
> Socialstream Providers component

This leads me to believe that I need to alter `/joelbutcher/socialstream/Providers.php` - which seems not to be published. I search my codebase for `hasBitbucketSupport` and the only place that the string is found is as above.

Would appreciate any help you can provide with this.

Many thanks

**Comment by rightwayround** [comment]
... I have to add the Provider to /config/socialstream.php. That is looking at /vendor/joelbutcher/socialstream/src/Providers.php for the class names of the providers I am adding.

Do I need another class that extends providers I wonder ...

**Comment by rightwayround** [comment]
I have figured this out. Would it be appreciated if I contributed back to documentation? Could do a PR for README?

**Comment by joelbutcher** [comment]
@rightwayround feel free to submit a PR if you think it solves an existing problem

**Comment by joelbutcher** [comment]
@rightwayround there is a public `enabled` method in `Providers.php`. The `hasBitbucketSupport` method you mentioned above is used in the `socialstream-providers.blade.php` file for the Livewire stack. For reference , this method just calls the `enabled` method like so:

```php
return static::enabled(static::bitbucket());
```

> The `bitbucket()` method just returns a string value for the provider name, in this case, that's just `"bitbucket"`.

If you have a provider that you're adding that's not supported natively by [Laravel Socialite](https://github.com/laravel/socialite/tree/5.x/src), you should add this as a string to the config providers array, then add the following condition where the logic is needed:

```php
if (\JoelButcher\Socialstream\Providers::enabled("my-custom-provider")
{
    // ...
}
```

**Comment by joelbutcher** [comment]
Closing this issue due to the above merge and release of v3.4.0
