### ISSUE TITLE
[BUG] Attempt to read property "password" on null

### ISSUE THREAD

**Issue by luiyongsheng** [joelbutcher/socialstream#17]
When rendering Inertia pages for guests, this error appears.

![image](https://user-images.githubusercontent.com/13586871/103447203-f56f2380-4cc2-11eb-8fbc-1cdeec9b096f.png)

![image](https://user-images.githubusercontent.com/13586871/103447190-c953a280-4cc2-11eb-889c-ab3d486fdf00.png)

**Comment by joelbutcher** [comment]
Hi @luiyongsheng thanks for reporting this. Please can you list the steps to reproduce?

**Comment by luiyongsheng** [comment]
I have routes that render Inertia pages that are exposed to anyone without `auth` middleware.
But after I installed socialstream, visiting those routes will result in the error mentioned above.

To reproduce:

1. Create a test route
```
Route::get('/test', function () {
    return Inertia::render('Home');
});
```
2. Install and use `socialstream`
3. Visit `{url}/test`

**Comment by joelbutcher** [comment]
Great, thanks!
