### ISSUE TITLE
[bug] Login with Google on Login screen

### ISSUE THREAD

**Issue by subdesign** [joelbutcher/socialstream#170]
**Describe the bug**
if I use the OAuthControlller as is, when I try to log in with google provider on the login page, I get the _An account with this Google sign in was not found_.. message.

I dig in the code and found the following:

if I remove the session check from the if statement below, it works, creates the user, adds provider record and connects the two tables, even logs in the user.

```php
if (FortifyFeatures::enabled(FortifyFeatures::registration()) && session()->get('socialstream.previous_url') === route('register')) {
...
}
```
why the script only from Register page registers the user, and not from Login page? Maybe I don't see the point.

**Expected behavior**
Should log in from the Login page even I don't have any user in the database.

**Screenshots**
<img width="497" alt="Screenshot 2022-01-18 at 17 39 14" src="https://user-images.githubusercontent.com/691695/149979949-029b5ca0-c1dd-47f4-a2aa-5563acc2ff2d.png">

**Environment context**
- Socialstream version: 3.3
- Jetstream stack: Inertia
- Laravel version: 8.79.0
- PHP version: 7.4.25

**Comment by Sairahcaz** [comment]
You need to enable [Features::createAccountOnFirstLogin](https://github.com/joelbutcher/socialstream/blob/3.x/config/socialstream.php#L48)

**Comment by subdesign** [comment]
Thanks
