### ISSUE TITLE
[bug] file_put_contents(/x): Failed to open stream: Permission denied - issue persists

### ISSUE THREAD

**Issue by ejntaylor** [joelbutcher/socialstream#174]
**Describe the bug**

I saw recent PR here for this issue: https://github.com/joelbutcher/socialstream/issues/157

However I still get this error:

`file_put_contents(/tmp61ede1ff-2eff-49e4-8c91-b1cfdcc87817): Failed to open stream: Permission denied`

from

`file_put_contents($file = sys_get_temp_dir().Str::uuid()->toString(), file_get_contents($url));`

I have tried checking perms for storage and ownership. I even spun up a new server on DO with Forge and the error persists.

Any ideas? 

**To Reproduce**
1. Go to [Coderbud](https://coderbud.io)
2. Click on 'Login with Github in top right'
3. Error happens when saving profile avatar

**Expected behavior**
No error -saves image

**Screenshots**

<img width="1255" alt="image" src="https://user-images.githubusercontent.com/2080025/151435925-de1c20b2-118e-41fb-bcc0-0dd06525aa14.png">

<img width="800" alt="image" src="https://user-images.githubusercontent.com/2080025/151435962-729a760b-f47c-4892-96b4-0d3749ba18e9.png">

**Environment context**
- Socialstream version: 3.3.0
- Jetstream stack: Inertia 
- Laravel version: 8.4.0
- PHP version: 8.0.14

**Comment by aidanthewiz** [comment]
This appears to be fixed here: d406cd7, but has not been released.

**Comment by ejntaylor** [comment]
Thanks and hope it gets merged soon. I'm just glad I'm not going mad after trying everything I could think of!

**Comment by joelbutcher** [comment]
@ejntaylor this has been fixed in release 3.4.0
