### ISSUE TITLE
[3.x] Check registration feature is enabled when handling errors

### ISSUE THREAD

**Issue by illambo** [joelbutcher/socialstream#180]
https://github.com/joelbutcher/socialstream/blob/9214d398847aef2225fcee5b0d47740eaf103b1d/src/Http/Controllers/OAuthController.php#L105

I wanted to point out that I think the configuration check is missing.
Thanks.

**Comment by joelbutcher** [comment]
@illambo great spot, thanks! I'll take a look at this ASAP
