### ISSUE TITLE
How to redirect the page for AccountCompletion after the registration[bug]

### ISSUE THREAD

**Issue by james-wong123** [joelbutcher/socialstream#185]
**Describe the bug**
I would like to generate a redirect if the account registration is not complete, but `GenerateRedirectForProvider` is not in `app/Actions/Socialstream` not sure what happened here.

**To Reproduce**

**Expected behavior**
I would like the user to complete the Registration if `username` field is null etc

I have edited the `CreateUserFromProvider.php` but not sure this work

```
return DB::transaction(function () use ($provider, $providerUser) {
            return tap(User::create([
                'name' => $providerUser->getName(),
                'username' => $providerUser->getNickname(),
                'email' => $providerUser->getEmail(),
            ]), function (User $user) use ($provider, $providerUser) {
                $user->markEmailAsVerified();

                // if username is null redirect to create username
                if ($providerUser->getNickname() == null) {
                    return Socialite::driver($provider)
                        ->scopes(['*'])
                        ->with(['response_type' => 'token'])
                        ->redirect(route('register.complete'));
                }

```
**Screenshots**

**Environment context**
- Socialstream version: 3.4.1
- Jetstream stack: Inertia
- Laravel version: 9.6.0
- PHP version: 8.1.2

**Comment by joelbutcher** [comment]
Hey @james-wong123 Please can you provide the correct Socialstream version you are using? The latest 2.x release is 2.5.1, but you've put 2.6 as the version causing the problem! 😅

**Comment by james-wong123** [comment]
@joelbutcher, haha sry for the wrong version 🤣

**Comment by joelbutcher** [comment]
@james-wong123 thanks for updating, will try and take a look at this this afternoon

**Comment by james-wong123** [comment]
@joelbutcher, Do I have to generate the redirect in `App/Providers/SocialstreamServiceProvider.php/` after the registration, if the given info is not complete. i.e `username`

**Comment by joelbutcher** [comment]
What you're doing seems wrong `Socialite::redirect()` is the external redirect to connect to an oauth provider (I.e. redirect to Google / Facebook). 

What you're doing in `CreateUserFromProvider.php` is "redirect to {provider} after returning from {provider} to create a user".

**Comment by james-wong123** [comment]
@joelbutcher, 

First, the user registers an account using `socialstream`, obviously not all the 3rd party OAuth provides a `username`, so we would require to redirect the user for the account completion. 😊

**Comment by joelbutcher** [comment]
Yeh best approach is to use something like `RequiresUsername` middleware and wrap all routes with that, then redirect users to the form they should use to set their username. Similar to Laravels own `verified` middleware for ensuring users verify their email address

**Comment by james-wong123** [comment]
@joelbutcher, Thx !
