### ISSUE TITLE
Change Inertia stubs to use Composition API

### ISSUE THREAD

**Issue by ibnu-ja** [joelbutcher/socialstream#191]
**What problem does this feature request solve?.**
Current Socialstream stack use Options API but since [v2,7.0](https://github.com/laravel/jetstream/releases/tag/v2.7.0), Jetstream use Composition API. It would be nice if Socialstream also implement Composition API 

**Describe your proposed solution**
Convert option api stubs to composition api

**Environment context**
- Socialstream version: 3.4.2
- Jetstream stack: Inertia

**Comment by ibnu-ja** [comment]
anyone working on this? if not please assign me

**Comment by joelbutcher** [comment]
@ibnu-ja please can you send in a PR for this? Please update Jestream to the version where the composition API is support.
