### ISSUE TITLE
[bug] Compatibility with Laravel Passport

### ISSUE THREAD

**Issue by MillerAdulu** [joelbutcher/socialstream#192]
**Describe the bug**

Got an error `Driver [authorize] not supported` on a fresh project with SocialStream and Passport. Turns out, 

**To Reproduce**
1. Install Passport and SocialStream
2. Use https://oauthdebugger.com/ to prepare an Oauth request so that the authorization which has social stream installed can show the login page
3. Paste the URL in the browser window

**Expected behavior**
That a user is led straight to the login page

**Environment context**
- Socialstream version: ^3.4
- Jetstream stack: Livewire
- Laravel version: ^9.11
- PHP version: ^8.0

**Cause**
This error is caused by how Socialite generates routes. Such that, when passport is visiting `oauth/authorize` to authorize, Socialite thinks it's a social media driver called `authorize` so when the framework boots and the URLs are generated, Social tries to redirect to this URL the way it would something like Google or Facebook, resulting in the error above. 

**Solution**
Add passport routes to `AuthServiceProvider.php` `boot` method as follows:
```php
Passport::routes(
                options: [
                    'prefix' => 'passport-oauth',
                ]
            );
```
This way, passport URLs are different and they don't collide with SocialStream. A point to note, having it as `oauth-passport` won't work.

**Comment by joelbutcher** [comment]
@MillerAdulu if the above solution fixes the problem, what do you want us to do with this package? We're not an official Laravel package and there no doubt other packages that conflict with other first-party Laravel packages

**Comment by MillerAdulu** [comment]
@joelbutcher 

For documentation purposes in case someone is looking for the solution should it happen for them. Going ahead to close it now.

**Comment by joelbutcher** [comment]
@MillerAdulu documentation has been added [here](https://github.com/joelbutcher/socialstream/commit/4fccaa4697a80c854619b8029c1c828ae5d81809)
