### ISSUE TITLE
 Call to undefined method JoelButcher\Socialstream\Providers::shopify()[bug]

### ISSUE THREAD

**Issue by pramodwagh** [joelbutcher/socialstream#195]
**Describe the bug**
Hello, I am trying to add a Shopify provider but facing ' Call to undefined method JoelButcher\Socialstream\Providers::shopify()' this error

**To Reproduce**
1. Go to 'socialstream.php file and add Providers::shopify()'
2. got to the terminal and run PHP artisan migrate

**Screenshots**
![image](https://user-images.githubusercontent.com/10533044/177084771-d72d9431-e03d-4df2-9955-780258497879.png)

**Comment by joelbutcher** [comment]
Shopify isn't a supported Socialite provider. If you wish to use a custom provider, you will need to implement this yourself using SocialiteProviders. Please refer to this part of the README documentation

**Comment by N30** [comment]
I am having a hard time with this too. Did not find anything helpful in the documentation, now that I have SocialStream between Jetstream and Socialite I can not figure out how to implement socialiteproviders.com community packages, any advice? Does Social Stream integrate Socialite with its full functionality? With the 3rd pardy providers you normally have to overrride the default  Provider loaded in config/app.php but I can't do that now either. Please advise.

**Comment by joelbutcher** [comment]
> I think the documentation should mention the EventServiceProvider that is needed to add from socialliteproviders.com

This is mentioned in their docs. This package is unrelated to socialite providers, but by the nature that is supports all Socialite options, it easily supports the socialiteprovider.com additions for Laravel. Please refer to and read their documentation in it's entirety for integrating one of their providers.

You will need to define:
- Icon for the provider
- Append the "Login with [X]" action to `Socialstream.vue` or `socialstream.blade.php`
