### ISSUE TITLE
Installation steps broken with vite introduction in Laravel

### ISSUE THREAD

**Issue by ayushghosh** [joelbutcher/socialstream#196]
You get error.

Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: http://0.0.0.0:5173/resources/js/Pages/Auth/Login.vue

I was able to update the paths and make it work for now.

**Comment by joelbutcher** [comment]
Oops, looks like I missed the Vite release.

I'll take a look at this tonight - thanks for the spot!

**Comment by joelbutcher** [comment]
Hi @ayushghosh I've just tried to replicate this with a fresh install, but everything seems to be working – are you working on a fresh application, or upgrading an existing one?

**Comment by joelbutcher** [comment]
This has been fixed with release [v3.6.1](https://github.com/joelbutcher/socialstream/releases/tag/v3.6.1)
