### ISSUE TITLE
[bug] larastan access to an undefined property $token

### ISSUE THREAD

**Issue by Wit3** [joelbutcher/socialstream#197]
**Describe the bug**
If i run larastan (phpstan) the stub action createConnectedAcccount try to set $token

```
  Line   app/Actions/Socialstream/CreateConnectedAccount.php
 ------ ---------------------------------------------------------------------------
  29     Access to an undefined property Laravel\Socialite\Contracts\User::$token.
```

https://github.com/joelbutcher/socialstream/blob/4fccaa4697a80c854619b8029c1c828ae5d81809/stubs/app/Actions/Socialstream/CreateConnectedAccount.php#L29

But the abstract user doesn't implent this property.

**Environment context**
- Socialstream version: v3.5.0
- Jetstream stack:  Livewire
- Laravel version: 9.21.0
- PHP version: 8.1.7

**Comment by joelbutcher** [comment]
Unfortunately this is a side effect of using Laravel Socialite.

**Comment by joelbutcher** [comment]
Please see https://github.com/laravel/socialite/blob/9dfc76b31ee041c45a7cae86f23339784abde46d/src/One/User.php#L14
