### ISSUE TITLE
On fresh install - missing Label.vue [bug]

### ISSUE THREAD

**Issue by helloadmin** [joelbutcher/socialstream#223]
[vite:load-fallback] Could not load /resources/js/Components/Label.vue (imported by resources/js/Pages/Auth/Login.vue): ENOENT: no such file or directory, open '/resources/js/Components/Label.vue'

I installed a fresh Laravel from composer then installed Jetstream via composer (at which point no issues) then installed SocialStream via composer at which it failed on the standard npm run build  or npm run dev

I had a look at a project from 6 months back where I used social stream and the same page reference Login.vue.  In that version, the page references Jetstream/Label.vue which is missing in the install in question.

This version of the project has a /resources/js/Components/InputLabel.vue  which appears to have the same content as the Jetstream/Label.vue and is likely its intended reference.

As a workaround in my case, I have made a copy of InputLabel.vue and renamed it Label.vue

PHP 8.1.19
Laravel 9 - latest as of Sep 2022

As always,  your efforts are appreciated.  Thank you for the often thankless efforts and time in creating and maintaining this project.

**Comment by joelbutcher** [comment]
Resolved with release 3.8.0
