### ISSUE TITLE
Improve documentation about how to add a custom Socialite provider

### ISSUE THREAD

**Issue by baoc75** [joelbutcher/socialstream#226]
**What problem does this feature request solve?.**
- Although I have tried to read the documentation and go through Github Issues and PRs, all I could find is instructions about how to create a login button for a custom provider. 
- So far, I've added the provider's name to the configuration array, added custom icons, and modified the socialsteam.blade.php and connected-account.blade.php file to display the new provider. 

**Describe your proposed solution**
- I think that the documentation should show instructions on how to implement them properly, e.g., by publishing the Providers.php file to extend it.

**Describe alternatives you've considered**
N/A

**Environment context**
- Socialstream version: 3.8
- Jetstream stack: Livewire
- Laravel version: 9.0
- PHP version: 8.1.8

**Comment by joelbutcher** [comment]
> publishing the Providers.php file to extend it.

You don’t need to publish this file to be able to extend it. Please can you resubmit this to [joelbutcher/socialstream-docs](https://github.com/joelbutcher/socialstream-docs) and outline the specific steps you propose should be documented.

Thanks
