### ISSUE TITLE
Maybe not enforce fully qualified user return type in CreatesUserFromProvider contract?

### ISSUE THREAD

**Issue by inmanturbo** [joelbutcher/socialstream#249]
Should this contract enforce `App\Models\User` in return type? This make the contract unusable if the user model is moved. It would force someone for instance with an `App\Models\Auth` namespace to maybe stub out an abstract user class in the `App\Models` namespace just to satisfy the contract. Just a thought.

https://github.com/joelbutcher/socialstream/blob/6d072c1ef0a7ce415a238742c127d9e362f13d78/src/Contracts/CreatesUserFromProvider.php#L13

**Comment by joelbutcher** [comment]
Resolved in v4.0.1
