### ISSUE TITLE
Splade integration as and install option

### ISSUE THREAD

**Issue by CamKem** [joelbutcher/socialstream#259]
Hi, it would be great to get support for the [Splade](https://splade.dev/) (essentially inertia for blade components, with much more) 
as an install option for socialstream.

Also Laravel 10 support when you get around to it.

**Comment by joelbutcher** [comment]
@CamKem No plans to support Splade as it's not one of the options Laravel Jetstream supports.

Laravel 10 support was added here: #241 and released here: https://github.com/joelbutcher/socialstream/pull/241

**Comment by CamKem** [comment]
Thanks, it would be great if Jetstream starts supporting Splade, I see on the roadmap the Splade creators have planned for Jetstream support (hopefully sometime soon).

**Comment by joelbutcher** [comment]
I don't see Jetstream integrating with Splade, it's a mix match of stacks. It'll probably be up to Splade to integrate with Jetstream their side, which will be the same for Socialstream as well 👍
