### ISSUE TITLE
Support for customize OAuthController

### ISSUE THREAD

**Issue by illambo** [joelbutcher/socialstream#26]
Hi could you give me a tip on how to overwrite OAuthController and routings ?
I try with publishing _socialstream-routes_ but maybe I'm doing something wrong.
Thanks

**Comment by joelbutcher** [comment]
Why do you need to extend the functionality of these routes?

**Comment by illambo** [comment]
Hi, in the project i am following i would need to configure for a custom provider a _implicit grant_ and scopes (due to supplier specification),
so basically instead of:

```php
/**
 * Get the redirect for the given Socialite provider.
 *
 * @param  \Illuminate\Http\Request  $request
 * @param  string  $provider
 * @return \Symfony\Component\HttpFoundation\RedirectResponse
 */
public function redirectToProvider(Request $request, string $provider)
{
    session()->put('origin_url', back()->getTargetUrl());

    return Socialite::driver($provider)->redirect();
}
```

something like:

```php
/**
 * Get the redirect for the given Socialite provider.
 *
 * @param  \Illuminate\Http\Request  $request
 * @param  string  $provider
 * @return \Symfony\Component\HttpFoundation\RedirectResponse
 */
public function redirectToProvider(Request $request, string $provider)
{
    session()->put('origin_url', back()->getTargetUrl());

    if ($provider == ConnectedAccount::PROVIDER_NAME_MYIDP) {
    	return Socialite::driver($provider)->scopes(['*'])
                ->with(['response_type' => 'token']) // implicit grant
                ->redirect();
    }

    return Socialite::driver($provider)->redirect();
}
```

And in handleProviderCallback method instead of `$providerAccount = Socialite::driver($provider)->user();` this `$providerAccount = Socialite::driver($provider)->userFromToken($request->get('auth_token'));`

Also sometimes it is not possible to negotiate (long response times) the return address so it is useful to be able to customize it.

You have suggestions?

I think it is very useful to give the possibility to extend and customize the oauth controller and the routing paths.

**Comment by joelbutcher** [comment]
@illambo I've written a PR for this #27. Will be included in the V2 release.

**Comment by illambo** [comment]
Good thank u very much! But it doesn't seem possible to manage routings and handle callback action. 

What do you think about it?

**Comment by joelbutcher** [comment]
@illambo As I said, defining the same route in your `web.php` file and specifying your own controller method will override the route and controller method by Socialstream

**Comment by illambo** [comment]
Ok sorry, I'm sorry I didn't read that right.
Thank you very much!

**Comment by illambo** [comment]
Sorry if I write to you again but if I overwrite in this way (example):
```php
Route::get('/login/{provider}', [\App\Http\Controllers\OAuthController::class, 'redirectToProvider'])->name('oauth.redirect');
Route::get('/login/{provider}/callback', [\App\Http\Controllers\OAuthController::class, 'handleProviderCallback'])->name('oauth.callback');
```
I can't run `php artisan route:cache` because throw `Unable to prepare route [login/{provider}] for serialization. Another route has already been assigned name [oauth.redirect].`

Do you have suggestions about it?
Thanks

**Comment by joelbutcher** [comment]
You should publish the existing routes if you wish to modify them:

```sh
php artisan vendor:publish --tag= socialstream-routes
```

**Comment by illambo** [comment]
It works! Thank you very much and sorry for the trouble.
