### ISSUE TITLE
[bug] Unknown Middleware 

### ISSUE THREAD

**Issue by quansho** [joelbutcher/socialstream#264]
Hi,
How do you guarantee that the response should be exactly Response|RedirectResponse|JsonResponse, I have a BinaryResponse and that I should get an error?

JoelButcher\Socialstream\Http\Middleware\ShareInertiaData::handle(): Return value must be of type Illuminate\Http\Response|Illuminate\Http\RedirectResponse|Illuminate\Http\JsonResponse, Symfony\Component\HttpFoundation\BinaryFileResponse returned

**Environment context**
- Socialstream version: All at this time actual versions
- Jetstream stack: Inertia 
- Laravel version: 9.0
- PHP version: 8.2

**Comment by joelbutcher** [comment]
@quansho This was fixed in #263 but I've not yet tagged this, sorry. Will get that released today – thanks 👍
