### ISSUE TITLE
Unable to locate a class or view for component

### ISSUE THREAD

**Issue by pixsolution** [joelbutcher/socialstream#269]
Hello, I installed the package in a project that I was starting in laravel 9, where I already had jetstream 2.12 installed, and after the installation I got this error Unable to locate a class or view for component [authentication-card-logo] I see that it doesn't recognize all the jetstream blade components, why is it?

**Comment by joelbutcher** [comment]
Please only install this package into a fresh Laravel project - adding Socialstream to existing projects is not supported
