### ISSUE TITLE
When installing with Laravel Nova - dashboard will not load

### ISSUE THREAD

**Issue by helloadmin** [joelbutcher/socialstream#270]
When starting a new Laravel project that also includes Laravel Nova, /dashboard will not load.  Javascript error is:
Ziggy error: 'team' parameter is required for route 'teams.show'.

I've started a new project then added Nova then Jetstream, - /dashboard works
New project with Jetstream then Nova  -  /dashboard works
New project with Nova then Jetstream,  - / dashboard works  -> add Socialstream -> get the error
New project with Socialstream -  /dashboard works  -> add Nova -> get the error
New project with Nova,  /dashboard works -> add Socialstream -> get the error

I've been doing the same procedure for the last year without issue.  In the last month or so, this started to happen.  

Socialstream 

- Socialstream version: latest
- Jetstream stack: 3.2 Inertia 
- Laravel version: 10
- PHP version: 8.1

**Comment by CamKem** [comment]
Did you fix it, this usually just means you have turned on the Features::teams(['invitations' => true]), but you didn't select the teams function when you installed the package.
