### ISSUE TITLE
Disable Socialstream route registration

### ISSUE THREAD

**Issue by ibnu-ja** [joelbutcher/socialstream#273]
**What problem does this feature request solve?.**
Currently, there is no way to modify socialstream routes. This limitation prevents users from customizing the behavior of the routes according to their specific needs. Personally I'd like to register additional middleware to Socialstream routes.

**Describe your proposed solution**
I suggest adding a new method called ignoreRoutes() to the Socialstream package. This method should provide the ability to disable route registration, similar to how Jetstream and Fortify handle route customization.

```php
    /**
     * Configure Socialstream to not register its routes.
     *
     * @return static
     */
    public static function ignoreRoutes()
    {
        static::$registersRoutes = false;

        return new static;
    }
```

With the addition of this method, users will be able to selectively disable or modify specific routes to align with their application requirements. They might copy the routes and register them manually in `app/Providers/RouteServiceProvider.php`. This flexibility will enhance the customization capabilities of Socialstream and allow developers to have greater control over their application's behavior.

**Describe alternatives you've considered**
One alternative solution could be configuring route registration through the `config/socialstream.php` file. However, this approach might differ from how Jetstream and Fortify handle route registration configuration. To maintain consistency and make it easier for users familiar with Jetstream and Fortify, I believe it would be more appropriate to introduce a dedicated method, `ignoreRoutes()`, for socialstream.

**Environment context**
- Socialstream version: 4.1.3
- Jetstream stack: Inertia & Livewire
- Laravel version: 10.12 (any version supported by socialstream)
- PHP version: 8.2.3 (any version supported by socialstream)

**Comment by joelbutcher** [comment]
You can override the routes by duplicating the route declarations in `./routes/web.php`

**Comment by joelbutcher** [comment]
@ibnu-ja I believe that's a jetstream route and not something that I can control the ability to disable in my package
