### ISSUE TITLE
[bug] Wrong cast type

### ISSUE THREAD

**Issue by DubStepMad** [joelbutcher/socialstream#279]
**Describe the bug**
After following the v4.x upgrade guide I am presented with the following error:
`htmlspecialchars(): Argument #1 ($string) must be of type string, Illuminate\Database\Eloquent\Casts\Attribute given`

Now the new method `profilePhotoUrl` is called in blade like this: `{{ Auth::user()->profilePhotoUrl() }}` which is throwing the error.

User Model Method:
```
/**
 * Get the URL to the user's profile photo.
 *
 */
public function profilePhotoUrl(): Attribute
{
    return filter_var($this->profile_photo_path, FILTER_VALIDATE_URL)
        ? Attribute::get(fn() => $this->profile_photo_path)
        : $this->getPhotoUrl();
}
```

**To Reproduce**
1. Follow upgrade guide from v3 to v4

**Expected behavior**
For the avatar to be displayed as previously it did.

**Environment context**
- Socialstream version: 4.1.3
- Jetstream stack: Livewire
- Laravel version: 10.20.0
- PHP version: 8.2

**Comment by DubStepMad** [comment]
Little digging around and try this instead in the User Model and works as intended.

Not sure if is something to do with versions, but the Jetstream version I have is: v3.3.3

```
/**
 * Get the URL to the user's profile photo.
 *
 */
public function profilePhotoUrl()
{
    return $this->profile_photo_path
        ? Storage::disk($this->profilePhotoDisk())->url($this->profile_photo_path)
        : $this->defaultProfilePhotoUrl();
}
```

**Comment by joelbutcher** [comment]
Looks like the Laravel guys accepted a [PR](https://github.com/laravel/jetstream/commit/a365b6b0d69a6f3758406081f5dd6b4b43d202d8) for the way Jetstream handles profile photo URLs, which is a bit annoying – I'll make a PR to fix this on 2.x and 3.x
