### ISSUE TITLE
Socialite has added new LinkedIn OpenID provider

### ISSUE THREAD

**Issue by avdheshsolanki** [joelbutcher/socialstream#284]
Please add the support new LinkedIn OpenID provider, and the documentation to use it.

Since LinkedIn updated their APIs and deprecated the product "[Sign In with LinkedIn](https://learn.microsoft.com/nl-nl/linkedin/consumer/integrations/self-serve/sign-in-with-linkedin)" and changed it to "
Sign In with LinkedIn using OpenID Connect", as of the 1 aug 2023. When using Socialite::driver('linkedin')->stateless()->user(); the API endpoint /me has not enough permissions, the new endpoint is: /v2/userinfo with scope 'openid'.

It is also updated on Socialite here
https://github.com/laravel/socialite/pull/662

**Comment by joelbutcher** [comment]
Planning to work on this next week 👨🏻‍💻

Thanks for the heads up!
