### ISSUE TITLE
[bug]  User Token column too small

### ISSUE THREAD

**Issue by helloadmin** [joelbutcher/socialstream#287]
Hi Joel,  feel free to disregard if out of scope - of course.  

I got the socialiteproviders/azure working (ty), but when creating the user in laravel I get the error:

String data, right truncated: 1406 Data too long for column 'token' at row 1 

[app / Actions / Socialstream / CreateConnectedAccount.php : 18](phpstorm://open?file=%2Fvar%2Fwww%2Fprojects%2Fgettel%2Fapp%2FActions%2FSocialstream%2FCreateConnectedAccount.php&line=18)

Here is the token Azure gave me.

0.Ab0A0G4g_38HtEeJt7sdomuN8Upjujsl_fdGhIi7ULkEzb5uALQ.AgABAAIAAAAtyolDObpQQ5VtlI4uGjEPAgDs_wUA9P_PPPoogXYVXqURkUypfV8lmDspHZpkzi0-M7HosFNGqE15LY59qOR4nprvajuzfkeWV89Ymy_PLVSGCBvU93dasVU3CyySLq2_LcO3q55wa6cSzsc0Tqg3HZyb7k02zPUYx1uFJ2oa9DACJMVSuqsCI3UfWz_KY_rHJ4oBWewVODf6xY0wPgrlKft7rDcBcwbr4WtQAoy7o7V3gK_4x6FgnVWJb0Xp9O8Ee9Hr_Fg7dj_lCc9JmQ-Krc2r4ZdPptFird7hhHKPK-3zGP8t4713Nenno5yd0UODpyRLyCx-FRRq0kERE-YZiOZN7yTGftM-OTc774t0kVug_Ms-Z8Xq5tHpcKMI0iY2t7KTVW4Pi1UlkxDKtXBuBcRp8HdbSwME1Zo3G4VJspVO5dwf499P8--a6Lxw8ySZqHWUdXOMImceISiG1uSUZ-9vYqqXobV7slcVNefd0s1Sd0VM2MaWIfb0N60lyL3yCwIiyioD78T1YXHIs7KPJ5DQuTtT3WBgXKSyw36DeeKQRdWN6iyfDv-5X2cCbllD45ThZZKm0my9xYdcIkg24D3jQJGbZzZQRnal3ZPeA1uGRVyj4peOlybeHjdwzmZN7B5NaAMj5c9gHahRc_7mp82EFyBMBvmzn3b9QrlvqZs30f0heYS5hUYsUUVSCdD3gs5k6IfUtciR&session_state=1075dc6d-6894-43ac-b83b-86730bcae143&state=laEwjSTql8gE9Qw6HstGDyveYGLYoKKK8d7qtiFB

I'm going to manually increase the column size of Token.  Perhaps the default for this column added by socialstream should be increased by default.   I leave it with you..

**Comment by joelbutcher** [comment]
Hey @helloadmin, since azure isn't supported natively by Laravel themselves, I'm reluctant to start making changes for individual providers supported through this community package
