### ISSUE TITLE
2 routes are named oauth.callback

### ISSUE THREAD

**Issue by chris-sev** [joelbutcher/socialstream#288]
**Describe the bug**
I'm unable to run `php artisan route:cache` because there are 2 routes with the name `oauth.callback`

I believe it happened in [this commit](https://github.com/joelbutcher/socialstream/commit/006612bec90dff631726453fba86eb339224375c) yesterday: 

https://github.com/joelbutcher/socialstream/blob/4.x/routes/socialstream.php#L13-L14

Both the `Route::get` and `Route::post` are named `oauth.callback`

**To Reproduce**
1. Run `php artisan route:cache`

**Expected behavior**
Caching works

**Screenshots**
![CleanShot 2023-09-13 at 07 12 12@2x](https://github.com/joelbutcher/socialstream/assets/1857851/d0c12f53-e8bb-458d-b8ea-b7201bd5c951)

**Environment context**
- Socialstream version: 4.4.3
- Jetstream stack: Inertia / Livewire
- Laravel version: 10
- PHP version: 8.2

**Comment by joelbutcher** [comment]
Thanks! I've patched with [v4.4.4](https://github.com/joelbutcher/socialstream/releases/tag/v4.4.4)

**Comment by neopheus** [comment]
Hi @joelbutcher,

After updating to Socialstream v5.2, the php artisan route:cache still fails due to duplicate route names for oauth.callback.

Environment:

Socialstream v5.2
Laravel v10
PHP v8.2

**Comment by joelbutcher** [comment]
@neopheus can you test the changes made in [this PR](https://github.com/joelbutcher/socialstream/pull/313) to see if this resolves the issue for you?

**Comment by neopheus** [comment]
Yes
You can validate the PR
