### ISSUE TITLE
Bitbucket icon is hiding

### ISSUE THREAD

**Issue by Jayesh-Patidar** [joelbutcher/socialstream#289]
**Describe the bug**
I am using this package along with livewire. I enabled bitbucket provider but the icon is hidden.

**To Reproduce**
I am not sure whether it is happening in inertia or not but in livewire I am facing this issue.

**Screenshots**
I know how to fix the issue for my purpose but don't know how can I contribute to the package as the view files are not visible to me.

The class to align the bitbucket icon is missing.

![image](https://github.com/joelbutcher/socialstream/assets/56397949/1a5a6e42-672a-44b6-8623-94ecdd56867b)
![image](https://github.com/joelbutcher/socialstream/assets/56397949/ede1e68f-d7c0-4766-8137-2d2caf46d6fd)

If I add the class it is working fine.

![image](https://github.com/joelbutcher/socialstream/assets/56397949/287b144c-3960-4c11-ba76-be8b7fe19d67)
![image](https://github.com/joelbutcher/socialstream/assets/56397949/29e6cc69-8aab-4358-bcf4-e4646d5129e4)

Please fix this.

Thank you

**Comment by joelbutcher** [comment]
Fixed in v4.4.5
