### ISSUE TITLE
Slack icon is not visible

### ISSUE THREAD

**Issue by Jayesh-Patidar** [joelbutcher/socialstream#290]
**Describe the bug**
In livewire slack icon is missing in connected accounts list.

**To Reproduce**
1. Enable the slack provider
2. Login to the account either with provider or basic authentication
3. Open profile
4. Scroll down to connected accounts section

**Actual behavior**
In this section you will find only slack is mentioned and icon is missing.

**Expected behavior**
Slack icon should be visible.

**Screenshots**

![image](https://github.com/joelbutcher/socialstream/assets/56397949/17ee6b1c-9fb6-42f9-8d33-65a3f90b85ef)

**To fix**
Add one more case statement for slack and it will be fixed.

![image](https://github.com/joelbutcher/socialstream/assets/56397949/3a1d17b7-6a1d-43be-aeb3-27b7a2f55c05)

**Comment by joelbutcher** [comment]
@Jayesh-Patidar If your project was created as socialstream installed before slack support was added, you will need to manually update these files yourself. You can copy the SVG icon over from the files in socialstream's vendor directory.
