### ISSUE TITLE
[bug]: Error when the user has already Login with a Provider, but there is no user link to the account

### ISSUE THREAD

**Issue by Philrobots** [joelbutcher/socialstream#314]
**Describe the bug**
Here is our problem 💥

Once in a while, a user connected with the "Google" provider but the application breaks because the user has already login with the "Google" provider but there is no `$user` link to the account for whatever reason, mainly because the user is not found in the database. 

Basically, our applications break because the "$account"  variable has a user attributes `null`.

File : `AuthenticateOAuthCallback.php` line 89

![image](https://github.com/joelbutcher/socialstream/assets/47373969/e3a1933f-0dfe-4ef5-9599-0191642534da)

It would be great if you could add a verification to verify that the user link to the account is not null.

 If the user exists, continue, if not call the `register` method. 

**To Reproduce**

$account needs to have an attributes user that is null, and to not match in the first condition.

**Expected behavior**

To add this condition in the `authenticate` function

```
        // Add verification
        if (!$account->user) {
            return $this->register($provider, $providerAccount);
        }
 
        // Continues
        $user = $account->user;

        $this->updatesConnectedAccounts->update($user, $account, $provider, $providerAccount);

        return $this->login($user);
```

**Screenshots**

<img width="1191" alt="image" src="https://github.com/joelbutcher/socialstream/assets/47373969/acfd9845-c9a3-4381-beb1-239664404ee8">

**Environment context**
- Socialstream version: 5.2.0
- Jetstream stack: Inertia / Livewire
- PHP version: 8.1.0

**Comment by joelbutcher** [comment]
After taking a long look at this, I’m not entirely sure this is a bug. You cannot create a connected account instance without first creating the user instance (the `user_id` value on the `connected_accounts` table should link to the primary ID of a user.

If you have somehow managed to end up in this state, then I assume a user has previously deleted their account and you’ve subsequently not cascaded the deletion down to include any of their connected account relations.

**Comment by GabrielHDL** [comment]
This bug still exists, I have the same issue and no, I dont forget delete on cascade
