### ISSUE TITLE
hardcoded to redirect to /dashboard if laravel breeze

### ISSUE THREAD

**Issue by Supernova3339** [joelbutcher/socialstream#322]
### Stack

Breeze – Blade with Alpine

### Package Version

v5.0.3

### Laravel Version

v10.38.2

### Livewire Version

v3.3.3

### PHP Version

PHP 8.2.0

### Problem description

[socialstream](https://github.com/joelbutcher/socialstream/tree/5.x)/[src](https://github.com/joelbutcher/socialstream/tree/5.x/src)/[Actions](https://github.com/joelbutcher/socialstream/tree/5.x/src/Actions)
/AuthenticateOAuthCallback.php

the redirect route is hardcoded to 'dashboard' instead of RouteServiceProvider::HOME

### Expected behavior

redirects to the route specified, eg RouteServiceProvider::HOME route

would also be nice if it can utilize the feature used with registration that redirects to the previous route optionally

### Steps to reproduce

try to login with laravel breeze without a dashboard route, throws a 404.

1: install laravel
2: install socialstream 
3: set stack to breeze, blade with alpine
4: remove  dashboard route
5: bug occurs

### Reproduction repository

https://github.com/Supernova3339/ssreprodbug1

**Comment by joelbutcher** [comment]
Hey 👋🏻

Thanks for raising an issue with my package. Unfortunately I was unable to locate your reproduction repository. In order to save time and help me identify the issue at hand,  please update your issue report with a **VALID** reproduction repository URL.

When this has been done, please "at" me - this will send an alert to my GitHub notification feed and let me know this issue is ready for further investigation.

Thanks!

**Comment by Supernova3339** [comment]
> Hey 👋🏻
> 
> Thanks for raising an issue with my package. Unfortunately I was unable to locate your reproduction repository. In order to save time and help me identify the issue at hand, please update your issue report with a **VALID** reproduction repository URL.
> 
> When this has been done, please "at" me - this will send an alert to my GitHub notification feed and let me know this issue is ready for further investigation.
> 
> Thanks!

@joelbutcher I've added a reproduction repository per your request.

**Comment by joelbutcher** [comment]
@Supernova3339 Please test the mentioned PR (#325) and see if this resolves the problem for you.

**Comment by Supernova3339** [comment]
> @Supernova3339 Please test the mentioned PR (#325) and see if this resolves the problem for you.

gave it a go, works perfectly 🎉

**Comment by joelbutcher** [comment]
@Supernova3339 I've just pushed a rather large update to the branch, can you give it one more once over with your use-case to check all behaves as expected?
