### ISSUE TITLE
[bug] Running artisan view:cache throws exception DirectoryNotFoundException

### ISSUE THREAD

**Issue by illambo** [joelbutcher/socialstream#33]
**Describe the bug**
Run `php artisan view:cache` generate `Symfony\Component\Finder\Exception\DirectoryNotFoundException`

**To Reproduce**

```
php artisan view:cache
Compiled views cleared!

   Symfony\Component\Finder\Exception\DirectoryNotFoundException 

  The "[hidden-project-path]/vendor/joelbutcher/socialstream/src/../resources/views" directory does not exist.

  at vendor/symfony/finder/Finder.php:589
    585▕             } elseif ($glob = glob($dir, (\defined('GLOB_BRACE') ? \GLOB_BRACE : 0) | \GLOB_ONLYDIR | \GLOB_NOSORT)) {
    586▕                 sort($glob);
    587▕                 $resolvedDirs = array_merge($resolvedDirs, array_map([$this, 'normalizeDir'], $glob));
    588▕             } else {
  ➜ 589▕                 throw new DirectoryNotFoundException(sprintf('The "%s" directory does not exist.', $dir));
    590▕             }
    591▕         }
    592▕ 
    593▕         $this->dirs = array_merge($this->dirs, $resolvedDirs);

      +17 vendor frames 
  18  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

**Expected behavior**
Ability to cache views.

**Environment context**
- Socialstream version: 1.1.1
- Jetstream stack: Livewire
- Laravel version: 8.21.0
- PHP version: 7.4.12

**Comment by joelbutcher** [comment]
Hi @illambo please consult the Laravel documentation on the `cache:clear` artisan command.

My solution to this for you and anyone with this issue, would be to manually create the directory and then run the command.

**Comment by illambo** [comment]
I'm sorry "the insistence" but I don't understand, the problem is not given by `cache:clear` but by `view:cache` and seems related to the vendor.
Do you have any advice on this ? 
Thanks

**Comment by joelbutcher** [comment]
Sorry, I meant `view:cache`

**Comment by illambo** [comment]
Super and very kind too! Thanks!
