### ISSUE TITLE
RefreshToken for Google is not working

### ISSUE THREAD

**Issue by wassim** [joelbutcher/socialstream#335]
### Stack

Breeze – React with Inertia

### Package Version

v5.4

### Laravel Version

v11

### PHP Version

v8.3

### Problem description

I'm getting an error while retrieving a token with Google as provider `$user->getTokenFor('google')`

```php
ErrorException 

Declaration of JoelButcher\Socialstream\Concerns\RefreshesOAuth2Tokens::refreshToken(JoelButcher\Socialstream\ConnectedAccount $connectedAccount): JoelButcher\Socialstream\RefreshedCredentials must be compatible with Laravel\Socialite\Two\GoogleProvider::refreshToken($refreshToken)
```

### Expected behavior

Successfully retrieve a user token with Google as provider

### Steps to reproduce

```php
$user = User::first();
$user->getTokenFor('google')
```

### Reproduction repository

https://github.com/laravel/laravel

**Comment by joelbutcher** [comment]
Hey @wassim thanks for reporting your issue, however I can see that you've not provided a valid reproduction repository URL.

Unfortunately, I don't have time to build out a new project for each bug report.

Please provide a valid reproduction repository URL with steps required to reproduce that error. If possible, please provide a staging, or live testing environment with debug enabled so so can see a stack trace of the exact error you're getting in your APM / logs.

Thanks!
