### ISSUE TITLE
Service Provider is never published

### ISSUE THREAD

**Issue by LuisPassos** [joelbutcher/socialstream#356]
### Stack

Jetstream – Vue with Inertia

### Package Version

v6.0

### Laravel Version

v11.0

### PHP Version

PHP 8.2.0

### Problem description

The SocialstreamServiceProvider file is never published when installing socialstream. If any change is made in app/Actions/Socialstream then changes will not take effect. I would like to change Actions to add scopes, as described here: https://docs.socialstream.dev/getting-started/customization/socialite-redirect

### Expected behavior

SocialstreamServiceProvider should be published.

### Steps to reproduce

Install Laravel v11 project with Jetstream (installed using  Herd)
Run: composer require joelbutcher/socialstream 
Run: php artisan socialstream:install jetstream inertia

File will not appear and any changes to actions will not take effect

### Reproduction repository

https://github.com/LuisPassos/socialstream

**Comment by joelbutcher** [comment]
@LuisPassos Can you check out the branch on #357 and re-run the installer to see if that works for you? Cheers!

**Comment by LuisPassos** [comment]
Thank you @joelbutcher. Installer now adds the service provider. 
Cheers
