### ISSUE TITLE
This password does not use the Bcrypt algorithm.

### ISSUE THREAD

**Issue by bgencacat** [joelbutcher/socialstream#366]
### Stack

Jetstream – Livewire

### Package Version

6.1

### Laravel Version

11.9

### Livewire Version

3.0

### PHP Version

PHP 8.3.9

### Problem description

Trying to login with previously registered Google (didn't test with any other provider) account's email causes `This password does not use the Bcrypt algorithm.` error.

### Expected behavior

Should warn user to log in with related social provider if password column is empty.

### Steps to reproduce

First register/login with Google
Logout
Try to login with that registered email and random password.

### Reproduction repository

https://github.com/bgencacat/projectb

**Comment by joelbutcher** [comment]
Do you have the `authUnlinkedProviders` feature enabled?

**Comment by joelbutcher** [comment]
@bgencacat Thanks for this! Was a nice problem to start the day with :)

Please can you checkout the branch in that pull-request and verify the fix works for you (and doesn't break anything else)? 🙏

**Comment by bgencacat** [comment]
It's fixed! Thank you, you are awesome 💖

**Comment by joelbutcher** [comment]
@bgencacat released in v6.1.4
