### ISSUE TITLE
PHP 8.4 deprecates implicit nullable parameters

### ISSUE THREAD

**Issue by selfsimilar** [joelbutcher/socialstream#375]
### Stack

Other

### Package Version

v6.1.5

### Laravel Version

v11

### Livewire Version

v3

### PHP Version

PHP 8.4

### Problem description

Notices are shown for deprecated code usage: `Implicitly marking parameter $label as nullable is deprecated, the explicit nullable type must be used instead` in `Providers.php`. There may be more instances in the codebase of implicit nullable function parameters. I'm happy to try a open a PR to prep the codebase for a clean transition to PHP 8.4 compatibility, at least for this deprecation issue.

> Deprecated: JoelButcher\Socialstream\Providers::bitbucket(): Implicitly marking parameter $label as nullable is deprecated, the explicit nullable type must be used instead in ./vendor/joelbutcher/socialstream/src/Providers.php on line 155
> 
> Deprecated: JoelButcher\Socialstream\Providers::facebook(): 
 ./src/Providers.php on line 163
> Deprecated: JoelButcher\Socialstream\Providers::github():  ./src/Providers.php on line 171
> Deprecated: JoelButcher\Socialstream\Providers::gitlab(): ./src/Providers.php on line 179
> Deprecated: JoelButcher\Socialstream\Providers::google(): ./src/Providers.php on line 187
> Deprecated: JoelButcher\Socialstream\Providers::linkedin(): ./Providers.php on line 195
> Deprecated: JoelButcher\Socialstream\Providers::linkedinOpenId():  ./Providers.php on line 203
> Deprecated: JoelButcher\Socialstream\Providers::slack(): ./Providers.php on line 211
> Deprecated: JoelButcher\Socialstream\Providers::twitter(): ./Providers.php on line 221
> Deprecated: JoelButcher\Socialstream\Providers::twitterOAuth1(): ./Providers.php on line 229
> Deprecated: JoelButcher\Socialstream\Providers::twitterOAuth2(): ./Providers.php on line 237
> Deprecated: JoelButcher\Socialstream\Providers::addLabelFor(): ./src/Providers.php on line 242

### Expected behavior

No notices of deprecation

### Steps to reproduce

use PHP 8.4

### Reproduction repository

https://github.com/just-use-php8.4

### Relevant log output

```shell
Deprecated: JoelButcher\Socialstream\Providers::bitbucket(): Implicitly marking parameter $label as nullable is deprecated, the explicit nullable type must be used instead in ./vendor/joelbutcher/socialstream/src/Providers.php on line 155

Deprecated: JoelButcher\Socialstream\Providers::facebook(): Implicitly marking parameter $label as nullable is deprecated, the explicit nullable type must be used instead in ./vendor/joelbutcher/socialstream/src/Providers.php on line 163

Deprecated: JoelButcher\Socialstream\Providers::github(): Implicitly marking parameter $label as nullable is deprecated, the explicit nullable type must be used instead in ./vendor/joelbutcher/socialstream/src/Providers.php on line 171

Deprecated: JoelButcher\Socialstream\Providers::gitlab(): Implicitly marking parameter $label as nullable is deprecated, the explicit nullable type must be used instead in ./vendor/joelbutcher/socialstream/src/Providers.php on line 179

Deprecated: JoelButcher\Socialstream\Providers::google(): Implicitly marking parameter $label as nullable is deprecated, the explicit nullable type must be used instead in ./vendor/joelbutcher/socialstream/src/Providers.php on line 187

Deprecated: JoelButcher\Socialstream\Providers::linkedin(): Implicitly marking parameter $label as nullable is deprecated, the explicit nullable type must be used instead in ./vendor/joelbutcher/socialstream/src/Providers.php on line 195

Deprecated: JoelButcher\Socialstream\Providers::linkedinOpenId(): Implicitly marking parameter $label as nullable is deprecated, the explicit nullable type must be used instead in ./vendor/joelbutcher/socialstream/src/Providers.php on line 203

Deprecated: JoelButcher\Socialstream\Providers::slack(): Implicitly marking parameter $label as nullable is deprecated, the explicit nullable type must be used instead in ./vendor/joelbutcher/socialstream/src/Providers.php on line 211

Deprecated: JoelButcher\Socialstream\Providers::twitter(): Implicitly marking parameter $label as nullable is deprecated, the explicit nullable type must be used instead in ./vendor/joelbutcher/socialstream/src/Providers.php on line 221

Deprecated: JoelButcher\Socialstream\Providers::twitterOAuth1(): Implicitly marking parameter $label as nullable is deprecated, the explicit nullable type must be used instead in ./vendor/joelbutcher/socialstream/src/Providers.php on line 229

Deprecated: JoelButcher\Socialstream\Providers::twitterOAuth2(): Implicitly marking parameter $label as nullable is deprecated, the explicit nullable type must be used instead in ./vendor/joelbutcher/socialstream/src/Providers.php on line 237

Deprecated: JoelButcher\Socialstream\Providers::addLabelFor(): Implicitly marking parameter $label as nullable is deprecated, the explicit nullable type must be used instead in ./vendor/joelbutcher/socialstream/src/Providers.php on line 242
```

**Comment by joelbutcher** [comment]
PHP 8.4 is not released and is unsupported by Laravel at this time. We will rollout support for 8.4 along to align with Laravel's plans to adopt that language version in their core framework and their first-party packages.
