### ISSUE TITLE
Use Jetstream User Model

### ISSUE THREAD

**Issue by jomo77** [joelbutcher/socialstream#50]
**What problem does this feature request solve?.**
If the User or Team Model is not in the "App/Models" Directory the Package crashes cause the path is hardcoded in the source code.  

**Describe your proposed solution**
JetStream uses the "useUserModel" and "useTeamModel" Method to set the Jetstream User/Team Model.
The package should provide a similar option or just use the JetStream Models.

**Environment context**
- Socialstream version: 2.1
- Jetstream stack: 2.1 Inertia(tested) / Livewire (should be also affected)
- Laravel version: 8.12
- PHP version: 8

**Comment by joelbutcher** [comment]
Feel free to submit a PR

**Comment by joelbutcher** [comment]
@jomo77 Where is the hard-coding of these models causing you an issue? As far as I can see, it's in published (a.k.a modifiable) code?

**Comment by jomo77** [comment]
Hi Joel,

I just reinstalled the package and updated to 2.3. 

This time I skipped the installation command and edited my User Model by myself.

The Installation breaks, because this line:
        copy(__DIR__.'/../../stubs/app/Models/User.php', app_path('Models/User.php'));

After editing all published Actions and replaced:

@param  \App\Models\User  $user
with
@param  mixed  $user

and the user & team use paths.
 
everything is working as expected :)

Thx for your advice. 

Maybe just add a short section in the readme for other users.

**Comment by joelbutcher** [comment]
@jomo77 thanks for the detailed explanation.

Socialstream is designed to work with a fresh, default Laravel 8 installation, the same as Jetstream. 

Whilst having your models out of the (admittedly new) Models folder breaks the package. If you install on a fresh Laravel 8 install, nothing breaks.

I plan on removing the type hints that cause the error for you in 3.x
