### ISSUE TITLE
Youtube guide

### ISSUE THREAD

**Issue by a0981456759** [joelbutcher/socialstream#56]
Could you record the guide video to implement the third-party login like FB or google?
It glad that you create an awesome tool

**Comment by luiyongsheng** [comment]
> Could you record the guide video to implement the third-party login like FB or google?
> It glad that you create an awesome tool

如果寫一篇Medium文章怎麼樣？

**Comment by joelbutcher** [comment]
I have no plans to do a YouTube video for this currently. If you need a guide, this should provide a good starting point: https://joelbutcher.medium.com/socialstream-laravel-socialite-meets-jetstream-33f997cff3e1
