### ISSUE TITLE
[bug] InvalidStateException on Safari only

### ISSUE THREAD

**Issue by luiyongsheng** [joelbutcher/socialstream#65]
When attempting to login(create user) using Safari, Chrome, and Firefox, only **Safari** returned `InvalidStateException`.

**Environment context**
- Socialstream version: 2.3.0
- Jetstream stack: Inertia
- Laravel version: 8.25.0
- PHP version: 8.0.1

**Comment by luiyongsheng** [comment]
Solution:
[source](https://stackoverflow.com/a/60997974)

**config/session.php**

`'secure' => env('SESSION_SECURE_COOKIE', true), // or set it to true in your .env file`

...

`'same_site' => "none",`

**Comment by joelbutcher** [comment]
Odd, I tend to do all my initial E2E testing in Safari as I know that it is prone to exposing problems (such as date and time input types (neither work!) 

Thanks for the quick resolution.
