### ISSUE TITLE
[bug] Column 'token' cannot be null with socialiteproviders

### ISSUE THREAD

**Issue by Brouilles** [joelbutcher/socialstream#67]
**Describe the bug**
Hi! Thanks for you work.
I try to implement a steam login with https://socialiteproviders.com/Steam/#installation-basic-usage. But, when I try to link my Steam account I have this error:
```
 Integrity constraint violation: 1048 Column 'token' cannot be null (SQL: insert into `connected_accounts` (`user_id`, `provider`, `provider_id`, `name`, `nickname`, `email`, `avatar_path`, `token`, `secret`, `refresh_token`, `expires_at`, `updated_at`, `created_at`)`
```

With the following values (I have edited):
```
values (1, steam, 25461145018390218, ?, contact, ?, https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/fe/fes49e7fb8e1997310d705b2a6158ff8dc1cdfeb_medium.jpg, ?, ?, ?, 2021-02-02 15:14:01, 2021-02-02 15:14:00, 2021-02-02 15:14:00))
```

**To Reproduce**
1. Install socialstream
2. Follow socialiteproviders installation guide https://socialiteproviders.com/usage/
3. Follow https://socialiteproviders.com/Steam/#installation-basic-usage

**Expected behavior**
Link or create the account (I have modify the jetstream migration to accept empty name & email. I prompt the user after the account creation).

**Environment context**
- Socialstream version: 2.3.0
- Jetstream stack: Livewire
- Laravel version: 8.25.0
- PHP version: 7.4.10

**Comment by Brouilles** [comment]
So, I see the Provider don't return a token. But I don't know how can do.

**Comment by joelbutcher** [comment]
You'll need to add `?response_type=token` as a query string param's. If you're on V2, you can create your own implementation of `JoelButcher\Socialstream\Contracts\ GeneratesProviderRedirect::class` and add the following to the `generate` method. 

```php
return Socialite::driver('steam')->with(['response_type' => 'token'])->redirect();
```

Hopefully that should help - let me know how you get on!

**Comment by Brouilles** [comment]
Thanks for your anwser!
I have make my implementation and modify edit the `SocialstreamServiceProvider` has follow: 
```
        // Socialstream::generatesProvidersRedirectsUsing(GenerateRedirectForProvider::class);
        Socialstream::generatesProvidersRedirectsUsing(CustomGeneratesProviderRedirect::class);
```

My `CustomGeneratesProviderRedirect` is also called (I check with the Logger) and go inside the if 'steam' provider. But I always have the same problem. 
```
public function generate(string $provider)
    {
        if ($provider == 'steam')
        {
            return Socialite::driver('steam')
                ->with(['response_type' => 'token'])->redirect();
        }
        else
        {
            return Socialite::driver($provider)->redirect();
        }
    }
```

So `Integrity constraint violation: 1048 Column 'token' cannot be null `. with `?` in the values, at the column of the token.

**Comment by joelbutcher** [comment]
Okay, this doesn't appear to be an issue with the package as the intended providers for Socialite have all returned some sort of token to populate this field. You'll just have to write a migration to make that column accept `NULL`.

I'll make a note in the SocialiteProvidiers section in the README at some point today

Thanks for the spot!
