### ISSUE TITLE
Generate Provider Callback similar to redirectForProvider

### ISSUE THREAD

**Issue by PatrickOgilvie** [joelbutcher/socialstream#70]
Firstly, I'd like to say that this is a really clean, useful package and I wouldn't be here to suggest a feature if I didn't feel that way.

The Issue:

For certain providers, especially Facebook, it is crucial that you can extend the handleProviderCallback method in the OAuthController. This could be for a few reasons, but a couple that really stand out are:

- Every time a user uses the Facebook oauth flow to login the token is changed, and each time it is a short-life token. Only lasts a couple of hours. You then have to exchange that token for a long-life token through the Facebook API. 

-  Facebook tokens generated have permissions tied to that token at the point of creation (each and every login). A user could create a token and the next time they log in using the facebook oauth flow, toggle a permission that the app requires to function and there is currently no easy way to inspect this before an error is triggered. 

Suggested Solution:

Ideally I'm able to intercept that part of the socialstream login flow exactly how Socialstream::generatesProvidersRedirectsUsing() can be used to extend the redirect. 

I'm going to check out exactly how you implemented the provider redirect override and try to port that to the provider callback. I'm not exactly sure where to start because I've never tried to extend a package with an Action yet, but I'll get to work! 

No environmental context required.

**Comment by joelbutcher** [comment]
Events are fired whenever a `ConnectedAccount` is created. You _could_ hook into this event and fetch the long-lived token in a background job or listener and store it against the corresponding record in the database.

**Comment by PatrickOgilvie** [comment]
Yeah this would be an acceptable way to handle it, thank you for that suggestion. My issues are only with one particular provider because my use-case only requires facebook, there could still be other reasons that people may wish to inspect each login callback for all sorts of providers. As these companies all tighten up their data practices I'm very keen to always be respectful of permissions and what not, so inspecting that as part of the oauth flow would be helpful in keeping all of that logic together. 

I'm looking at #27, and using that as a starting point and I _think_ it looks easy enough to extend for myself, if it works I'll try and work out how to PR it (not used github in this way before). This is a great little package though that bridges that tiny gap between Socialite and Jetstream so well, so thank you for creating it.

**Comment by joelbutcher** [comment]
You could have a listener on the event and dispatch a different job for different providers. Although we're now entering the realm of design patterns/practices which are different from app to app

**Comment by joelbutcher** [comment]
@PatrickOgilvie Any progress on this?

**Comment by PatrickOgilvie** [comment]
I did get it working how I would like it to using #27, however in the end I ripped it all out and just rolled a way more basic socialite without any packages. Since my use-case was a bit more specific, and the OAuthController ends up getting totally cannibalised I can safely close this issue, thanks for your time!
