### ISSUE TITLE
What does this feature?

### ISSUE THREAD

**Issue by FoksVHox** [joelbutcher/socialstream#74]
Hello!

Firstly I want to say this a great package, but I wonder what does the `Features::createAccountOnFirstLogin()` do?

**Comment by joelbutcher** [comment]
Hi, it creates an account if the user is attempting to log in with a provider and email that isn't registered in the database. When disabled, it redirects you back to the login route and asks the user to register instead.

**Comment by FoksVHox** [comment]
Yeah found out
