### ISSUE TITLE
[object Object] error message at existing account

### ISSUE THREAD

**Issue by NetRally** [joelbutcher/socialstream#83]
Hello!
When I try connect an existing accont from social provider I get the prompt that it was not successfull but the message is only [object Object]

**Comment by joelbutcher** [comment]
Hi @NetRally 

Please can you provide more info such as the stack you were using when you got this error. Every bit of information helps!

Thanks

**Comment by NetRally** [comment]
I registered one account via Google and one with form. I logged in with the second one and made a try what happened when  I try to connect the Google account to this and then was this message. I think it should be a prompt that this account is already registered or connected or something similar.

**Comment by joelbutcher** [comment]
@NetRally What branch are you using? I've just tested this on a fresh install from the latest release and it's working fine in all scenarios for me

**Comment by joelbutcher** [comment]
Closing this as I cannot replicate, if you continue to get this error, please @ mention me so I get an email notification
