### ISSUE TITLE
How to get the provider details used for current authentication session?

### ISSUE THREAD

**Issue by AnandPilania** [joelbutcher/socialstream#9]
Hi @joelbutcher, first of all, THANKS A TON for this package.

For ex, I added three providers (facebook, google & twitter) and used them alternatively for login.

So, how can I know that which provider is used for current login.

**Comment by joelbutcher** [comment]
@AnandPilania No problems, it needed to be done!

Currently there isn't a way to do this from within the package itself, but if you wanted to write a PR for it, then my recommendation would be to add a `current_provider_id` column to the users table and update the controller logic to set the ID on login. Hope this helps!

**Comment by AnandPilania** [comment]
> @AnandPilania No problems, it needed to be done!
> 
> Currently there isn't a way to do this from within the package itself, but if you wanted to write a PR for it, then my recommendation would be to add a `current_provider_id` column to the users table and update the controller logic to set the ID on login. Hope this helps!

I already done this via:

1. `using_provider` column (which holds `provider_name`) in `users` table,
2. update `using_provider` on `auth` AND `logout`

If you want/need, then I can create a PR.

Thanks & Regards

**Comment by joelbutcher** [comment]
I personally wouldn't make `name` nullable. I'd use the name of the provider used to register. Any thee name at that point is redundant. If the account details are wrong, then the user can always set a password and delete the account. 

Same for avatar. If one exists on the provider, I'd set the profile picture url from Jetstream to the avatar URL of the provider used to register
