### ISSUE TITLE
Use Named Error Bags

### ISSUE THREAD

**Issue by AFink** [joelbutcher/socialstream#90]
**What problem does this feature request solve?.**
In my Login-form I only have the input errors (`<x-jet-input-error for="password"></x-jet-input-error>`), not the whole error loop. If I reenable the whole error loop `<x-jet-validation-errors />`, I would get the socialstream-errors AND the validation errors TWICE (in the input errors and in the error loop).

**Describe your proposed solution**
It should be possible to use https://laravel.com/docs/8.x/validation#named-error-bags for the OAuthController, so you can still use the default loop, but you can also choose to only display the errors for socialstream.

**Environment context**
- Socialstream version: 2.4.0
- Jetstream stack: Livewire
- Laravel version: v8.32.1
- PHP version: v7.3.21

**Comment by joelbutcher** [comment]
You can make these changes in your application if it's required.

**Comment by joelbutcher** [comment]
Feel free to attempt a PR on this - happy to review any contributions from other dev's 😃
