### ISSUE TITLE
Problem with returning errors during login

### ISSUE THREAD

**Issue by illambo** [joelbutcher/socialstream#95]
php: 8.0.3
laravel/framework: 8.34.0
joelbutcher/socialstream: 2.4.1
laravel/jetstream: 2.2.4

Hello, I'm having trouble printing errors in login page, 
in example "sign in was not found"

https://github.com/joelbutcher/socialstream/blob/09fad4e4c88771f47b50b43b4fb3a2736e4bbadf/src/Http/Controllers/OAuthController.php#L156

error output is not printed but if I use default key parameters in _->withErrors_ method instead of _'socialstream'_ it works.

```php
if (! Features::createsAccountsOnFirstLogin() && ! $account) {
    return redirect()->route('login')->withErrors(
         __('An account with this :Provider sign in was not found. Please register or try a different sign in method.', ['provider' => $provider]) 
        /*,'socialstream'*/ 
    );
}
```

Do you have any suggestions?
Thanks!

**Comment by joelbutcher** [comment]
Have you updated your views to account for this? Try using `$errors->socialstream->first('<Your-field-name><')`

**Comment by NetRally** [comment]
You should separate the error bags, the default @if ($errors->any()) etc. worked only with jetstream errors. 
Place for example @if ($errors->socialstream->any()) to grab them.

**Comment by illambo** [comment]
Thanks! Sorry for the little know how :)
