### ISSUE TITLE
[bug] SetProfilePhotoFromUrl : file_get_contents()

### ISSUE THREAD

**Issue by luiyongsheng** [joelbutcher/socialstream#96]
**Describe the bug**
```file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0```

**To Reproduce**
1. Use AWS S3 bucket or any other similar storage service
2. Login a social account
3. See error

**Expected behavior**
Allow profile photo to be uploaded to bucket

**Screenshot**
<img width="619" alt="image" src="https://user-images.githubusercontent.com/13586871/112797093-7a3cc400-909d-11eb-824c-b5ec33f8c04e.png">

**Environment context**
- Socialstream version: 3.0.1
- Jetstream stack: Inertia
- Laravel version: 8.34.0
- PHP version: 8.0.3

**Comment by joelbutcher** [comment]
This is an extensible trait and you're free to alter the behaviour in your user model as you see fit for your specific use-case
